BEGIN;

DROP SCHEMA IF EXISTS mart CASCADE;
DROP SCHEMA IF EXISTS dwh  CASCADE;
DROP SCHEMA IF EXISTS stg  CASCADE;
DROP SCHEMA IF EXISTS ops  CASCADE;
DROP SCHEMA IF EXISTS raw  CASCADE;

CREATE SCHEMA raw;
CREATE SCHEMA stg;
CREATE SCHEMA dwh;
CREATE SCHEMA mart;
CREATE SCHEMA ops;

COMMIT;
